import { majorTopics, audienceSegments, keywordsData } from './data';
import './App.css';

function App() {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 p-4 sm:p-8 font-sans">
      <header className="text-center mb-12">
        <h1 className="text-4xl sm:text-5xl font-bold text-sky-400">Audience Insights: Independent.ie</h1>
      </header>

      <main className="max-w-6xl mx-auto space-y-16">
        {/* Major Topics Section */}
        <section>
          <h2 className="text-3xl font-semibold mb-6 text-sky-300 border-b-2 border-sky-500 pb-2">Major Topics</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {majorTopics.map((topic, index) => (
              <div key={index} className="bg-slate-800 p-6 rounded-lg shadow-lg hover:shadow-sky-700/50 transition-shadow duration-300">
                <h3 className="text-xl font-bold text-sky-400 mb-2">{topic.title}</h3>
                <p className="text-slate-300 text-sm">{topic.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Audience Segments Section */}
        <section>
          <h2 className="text-3xl font-semibold mb-6 text-sky-300 border-b-2 border-sky-500 pb-2">Audience Segments</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {audienceSegments.map((segment, index) => (
              <div key={index} className="bg-slate-800 p-6 rounded-lg shadow-lg hover:shadow-sky-700/50 transition-shadow duration-300">
                <h3 className="text-xl font-bold text-sky-400 mb-2">{segment.title}</h3>
                <p className="text-slate-300 text-sm">{segment.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Keywords Section */}
        <section>
          <h2 className="text-3xl font-semibold mb-6 text-sky-300 border-b-2 border-sky-500 pb-2">Target Keywords</h2>
          <div className="space-y-8">
            {keywordsData.map((keywordCategory, index) => (
              <div key={index} className="bg-slate-800 p-6 rounded-lg shadow-lg hover:shadow-sky-700/50 transition-shadow duration-300">
                <h3 className="text-xl font-bold text-sky-400 mb-3">{keywordCategory.category}</h3>
                <div className="flex flex-wrap gap-2">
                  {keywordCategory.keywords.map((keyword, kwIndex) => (
                    <span key={kwIndex} className="bg-sky-600 text-slate-50 px-3 py-1 rounded-full text-xs font-medium hover:bg-sky-500 transition-colors duration-200">
                      {keyword}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="text-center mt-16 py-6 border-t border-slate-700">
        <p className="text-sm text-slate-400">Generated by Manus AI | Audience Insights Tool</p>
      </footer>
    </div>
  );
}

export default App;

